name: ci
on: [push, pull_request]
jobs:
  tests:
    name: Test on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: "1.23.0"
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run tests
      run: |
        set -euo pipefail
        echo "Go version:"
        go version
        echo "Running tests..."
        
        # Run tests with proper error handling
        if ! go test -v; then
          echo "Error: Tests failed"
          exit 1
        fi
        
        echo "All tests passed successfully!"
      shell: bash
